language: node_js

node_js:
  - "lts/*"

cache:
  directories:
    - node_modules

before_script:
  - npm install

addons:
  chrome: stable

branches:
  only:
    - master

script:
  - npm run test:cover 
  - npm run codecov